const app=document.querySelector('#app');
const iconPaths={alarm:'M7 3 3 6m14-3 4 3M8 20l-2 2m10-2 2 2M12 8v5l3 2M20 13a8 8 0 1 1-16 0 8 8 0 0 1 16 0',calendar:'M5 5h14v16H5zM8 3v4m8-4v4M5 10h14m-10 4h1m4 0h1m-6 3h1',timer:'M9 2h6m-3 0v3m6 1 2-2M12 9v5l3 1M20 14a8 8 0 1 1-16 0 8 8 0 0 1 16 0',watch:'M12 7v6l4 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',settings:'M9 3h6l1 3 3 1 2 5-2 5-3 1-1 3H9l-1-3-3-1-2-5 2-5 3-1zM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0',plus:'M12 5v14M5 12h14',back:'m14 5-7 7 7 7M7 12h13',right:'m9 5 7 7-7 7',check:'m5 12 4 4L19 6',play:'m9 5 10 7-10 7z',pause:'M8 5v14m8-14v14'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${iconPaths[n]||iconPaths.alarm}"/></svg>`;
let page='home',taps=0,unlocked=false,toastTimer,editingId=null,repeat='单双休',stopwatchStart=0,elapsed=0,interval;
let alarms=[{time:'07:00',name:'工作日出发',repeat:'单双休',enabled:true},{time:'09:30',name:'周末，慢一点',repeat:'周末',enabled:false}];
const notes={home:[['先看到下一次，再看到列表','用一个清晰的大时间回答“明天几点响”。日期、重复规则和倒计时各就其位。'],['保留温暖，收紧留白','熟悉的日出色卡片，轻一点的阴影。已停用闹钟仍然保持可读。']],edit:[['保存，始终在手边','时间选择器收紧，底部按钮固定。无论滚动到哪里，都能完成设置。'],['规则选择，一眼看懂','常用重复方式直接可选；单双休给出清楚的补班说明。']],settings:[['设置按目的分组','本周安排、声音与提醒、关于。诊断收进可展开区域，减少翻找。'],['状态比说明更重要','清晰的白色开关滑块；用日期区间说明本周，不再暴露内部周序号。']],about:[['小秘密，有明确回应','点击 Logo，七个小圆点逐个亮起。第七下，奖励直接出现在当前视口。'],['一点惊喜，不打扰','暖色光晕、轻弹动画、一句属于战马的话。关闭后仍留在原来的页面。']],schedule:[['轮换与调休，分清层级','保留月历，让休息日更易辨认；用说明解释调休覆盖规则。']],timer:[['时间单位，不用猜','补上时、分、秒标注，常用时长直接选择。']],stopwatch:[['专注正在发生的时间','明确开始与暂停状态，把核心操作放在拇指容易触达的位置。']]};
function nav(){return `<nav class="nav" aria-label="主导航">${[['home','alarm','闹钟'],['schedule','calendar','日程'],['timer','timer','计时'],['stopwatch','watch','秒表'],['settings','settings','设置']].map(([id,i,t])=>`<button data-go="${id}" class="${page===id?'active':''}" ${page===id?'aria-current="page"':''}>${icon(i)}${t}</button>`).join('')}</nav>`}
function bar(title,back='home'){return `<header class="bar"><button class="icon-btn" data-go="${back}" aria-label="返回">${icon('back')}</button><h2>${title}</h2><span></span></header>`}
function switchHtml(id,on,label){return `<button type="button" class="switch" role="switch" aria-checked="${on}" aria-label="${label}" data-switch="${id}"></button>`}
function escapeText(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function home(){const enabled=alarms.filter(a=>a.enabled).sort((a,b)=>a.time.localeCompare(b.time));const next=enabled[0];return `<section class="scroll"><header class="topline"><div><small>9 月 19 日 · 星期六</small><h2>战马闹钟</h2></div><button class="icon-btn" data-go="about" aria-label="关于战马闹钟"><img class="avatar" src="../assets/icon.png" alt=""></button></header><section class="hero"><span class="overline">${next?'下一次响铃 · 明天':'今天，先好好休息'}</span><div class="hero-time">${next?next.time:'— : —'}</div><div class="hero-meta">${next?escapeText(next.name):'暂无待响铃闹钟'} <i class="dot"></i> ${next?escapeText(next.repeat):'随时添加'}</div><div class="countdown">${icon('alarm')}${next?'9 月 20 日 · 调休补班日':'开启一枚闹钟，准备下一次出发'}</div></section><div class="section-title"><h3>我的闹钟</h3><span>${alarms.length} 个闹钟 · ${enabled.length} 个开启</span></div>${alarms.map((a,i)=>`<article class="card alarm ${a.enabled?'':'off'}"><button class="alarm-edit" data-edit="${i}" aria-label="编辑${escapeText(a.name)}"><div class="alarm-time">${a.time}</div><div class="alarm-name">${escapeText(a.name)}</div><div class="subtle">${escapeText(a.repeat)}${a.repeat==='单双休'?' · 智能适配调休':''}</div></button>${switchHtml(i,a.enabled,a.name)}</article>`).join('')}<div class="week-note"><span class="badge">本周双休</span>调休以具体日期安排为准</div></section><div class="bottom-action"><button class="primary" data-new>${icon('plus')}添加闹钟</button></div>${nav()}`}
function edit(){const a=editingId===null?{time:'07:00',name:''}:alarms[editingId];return `${bar(editingId===null?'新建闹钟':'编辑闹钟')}<form id="alarm-form" class="scroll"><div class="form-card"><label class="form-label">响铃时间 · 24 小时制</label><div class="time-inputs"><input aria-label="小时" name="hour" type="number" min="0" max="23" required value="${a.time.split(':')[0]}"><span>:</span><input aria-label="分钟" name="minute" type="number" min="0" max="59" required value="${a.time.split(':')[1]}"></div><div class="time-caption">轻点数字，输入你想醒来的时间</div></div><div class="form-card"><label class="form-label">重复方式</label><div class="chips">${['仅一次','每天','工作日','周末','单双休','自定义'].map(t=>`<button type="button" class="chip ${repeat===t?'selected':''}" data-repeat="${t}" aria-pressed="${repeat===t}">${t}</button>`).join('')}</div><div class="days">${['一','二','三','四','五','六','日'].map((d,i)=>`<button type="button" aria-label="星期${d}" aria-pressed="${i<6}" class="${i<6?'selected':''}" data-day="${i}">${d}</button>`).join('')}</div><div class="context-note" id="repeat-note">${repeatNote()}</div></div><div class="form-card"><label for="alarm-name" class="form-label">闹钟名称（选填）</label><input class="field" id="alarm-name" name="name" maxlength="24" placeholder="例如：起床，去追今天的太阳" value="${escapeText(a.name)}"></div><div class="form-card"><div class="row"><strong>铃声</strong><select aria-label="铃声" class="chip"><option>晨光</option><option>默认</option><option>轻风</option></select></div><div class="row"><strong>渐强唤醒</strong>${switchHtml('fade',true,'渐强唤醒')}</div><div class="row"><strong>关闭任务</strong><select aria-label="关闭任务" class="chip"><option>无</option><option>算术题</option></select></div></div></form><div class="bottom-action"><p class="save-note">预览保存后，可在首页查看这枚闹钟</p><button class="primary" type="submit" form="alarm-form">保存闹钟</button></div>`}
function repeatNote(){return repeat==='单双休'?'单休周：周一至周六响铃。双休周：周一至周五响铃。法定调休优先。':repeat==='仅一次'?'仅在下一次指定时间响铃。':repeat==='自定义'?'点选上方日期，设置你的每周节奏。':'按所选周期重复，具体调休规则以正式应用为准。'}
function settings(){return `<section class="scroll"><header class="topline"><h2>设置</h2><span class="subtle">照顾你的每一种节奏</span></header><section class="card week-card"><span class="overline">本周安排</span><h3>9.14 — 9.20 <span class="badge">双休周</span></h3><p class="subtle">自动交替 · 下周为单休周</p><div class="chips"><button class="chip" data-week="单休">单休周</button><button class="chip selected" data-week="双休">双休周</button></div><div class="context-note">9 月 20 日为补班日，工作日闹钟正常响铃。</div></section><div class="settings-title">声音与提醒</div><div class="card settings-card"><div class="row"><div><strong>默认铃声</strong><small>为清晨留一点温柔</small></div><select class="chip" aria-label="默认铃声"><option>晨光</option><option>默认</option><option>轻风</option></select></div><div class="row"><div><strong>渐强唤醒</strong><small>音量缓缓增加</small></div>${switchHtml('fade',true,'渐强唤醒')}</div><div class="row"><strong>振动</strong>${switchHtml('vibrate',true,'振动')}</div><div class="row"><div><strong>夜间静音</strong><small>23:00—07:00 · 该时段闹钟静音</small></div>${switchHtml('night',false,'夜间静音')}</div></div><div class="settings-title">响铃保障</div><details class="card"><summary>权限与设备诊断 <span class="badge">查看状态</span></summary><p class="subtle">示例状态：通知已开启 · 精确闹钟已允许。<br>正式应用将在这里检查实际设备权限。</p><button class="text-button" data-tip="此处将进入设备权限检查，Demo 不更改系统权限">查看设备设置 →</button></details><button class="card row row-btn" style="padding:14px 18px" data-go="about"><div><strong>关于战马闹钟</strong><small>懂你的每一周</small></div><span class="row-right">v2.0.8 ${icon('right')}</span></button></section>${nav()}`}
function about(){return `${bar('关于战马','settings')}<section class="scroll"><div class="about-hero"><button class="logo-button" id="logo" aria-label="点击战马 Logo，累计七次唤醒彩蛋"><img src="../assets/icon.png" alt="战马"></button><h2>战马闹钟</h2><p>v2.0.8 · 懂你的每一周</p><div class="tap-progress" aria-label="彩蛋进度">${Array.from({length:7},(_,i)=>`<i class="${i<taps?'filled':''}"></i>`).join('')}</div><div class="egg-hint" aria-live="polite">${unlocked?'战马已醒，轻点可再见一面':taps?`再点 ${7-taps} 次，唤醒战马`:'有个小秘密，藏在战马身上'}</div></div><article class="card story"><h3>每一匹战马，都有自己的战场。</h3><p>有人周一到周五冲锋，<br>有人周六还在奔跑。<br><br>记住单双休，也记住调休。<br>只在该响的时候响，<br>把安心留给每一个清晨。</p><p class="sign">你负责好好睡，我负责准时叫醒。</p></article><p class="about-foot">为认真生活的你制作</p></section>`}
function schedule(){return `<section class="scroll"><header class="topline"><h2>日程</h2><span class="badge">本月安排</span></header><article class="card"><h3>2026 年 9 月</h3><div class="calendar">${['一','二','三','四','五','六','日'].map(d=>`<span class="subtle">${d}</span>`).join('')}<span></span>${Array.from({length:30},(_,i)=>`<span class="${i===18?'today':[4,5,12,24,25,26].includes(i)?'rest':''}">${i+1}</span>`).join('')}</div><div class="context-note">本周为双休轮换，9 月 20 日调休补班。<br>实际休息安排以日期标记为准。</div></article><p class="subtle">日历为本次界面提案的示例展示。</p></section>${nav()}`}
function timer(){return `<section class="scroll"><header class="topline"><h2>计时</h2><span class="subtle">给专注留一点时间</span></header><div class="card" style="margin-top:44px"><div class="timer-unit">时　 :　 分　 :　 秒</div><div class="timer-display" id="timer-value" style="margin:20px 0">00:05:00</div></div><div class="chips">${[1,3,5,10,15].map(n=>`<button class="chip ${n===5?'selected':''}" data-duration="${n}">${n} 分钟</button>`).join('')}</div><p class="subtle" style="text-align:center;margin-top:30px">选择一段时间，专心做一件小事。</p></section><div class="bottom-action"><button class="primary" data-tip="已预览开始状态；此 Demo 不触发真实计时通知">${icon('play')}开始计时</button></div>${nav()}`}
function stopwatch(){return `<section class="scroll"><header class="topline"><h2>秒表</h2></header><div class="timer-display" id="stopwatch-value">00:00.00</div><p class="subtle" style="text-align:center">把每一次投入，都算在时间里。</p></section><div class="bottom-action"><button class="text-button" id="reset-watch" style="width:100%">重置</button><button class="primary" id="start-watch">${icon('play')}开始</button></div>${nav()}`}
function render(){clearInterval(interval);stopwatchStart=0;elapsed=0;app.innerHTML=({home,edit,settings,about,schedule,timer,stopwatch}[page]||home)();document.querySelectorAll('[data-go]').forEach(b=>{if(b.closest('.screen-links'))b.classList.toggle('selected',b.dataset.go===page)});document.querySelector('#notes').innerHTML=(notes[page]||notes.home).map(([h,p],i)=>`<div class="annotation"><h3><span class="note-index">0${i+1}</span>${h}</h3><p>${p}</p></div>`).join('')}
function go(p){page=p;hideToast();if(p==='about'){taps=0;unlocked=false}render()}
function hideToast(){clearTimeout(toastTimer);document.querySelector('#toast').classList.remove('visible')}
function toast(t){const el=document.querySelector('#toast');el.textContent=t;el.classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(hideToast,2400)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.go){if(b.dataset.go==='edit'){editingId=null;repeat='单双休'}go(b.dataset.go)}if(b.hasAttribute('data-new')){editingId=null;repeat='单双休';go('edit')}if(b.dataset.edit!==undefined){editingId=Number(b.dataset.edit);repeat=alarms[editingId].repeat;go('edit')}if(b.dataset.switch!==undefined){const on=b.getAttribute('aria-checked')!=='true';b.setAttribute('aria-checked',String(on));if(page==='home'){alarms[Number(b.dataset.switch)].enabled=on;render();toast(on?'闹钟已开启（预览）':'闹钟已停用（预览）')}}if(b.dataset.repeat){repeat=b.dataset.repeat;document.querySelectorAll('[data-repeat]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b))});document.querySelector('#repeat-note').textContent=repeatNote();document.querySelectorAll('[data-day]').forEach((x,i)=>{const on=repeat==='每天'||repeat==='单双休'&&i<6||repeat==='工作日'&&i<5||repeat==='周末'&&i>=5;x.classList.toggle('selected',on);x.setAttribute('aria-pressed',String(on))})}if(b.dataset.day!==undefined){b.classList.toggle('selected');b.setAttribute('aria-pressed',String(b.classList.contains('selected')));repeat='自定义';document.querySelectorAll('[data-repeat]').forEach(x=>{x.classList.toggle('selected',x.dataset.repeat===repeat);x.setAttribute('aria-pressed',String(x.dataset.repeat===repeat))});document.querySelector('#repeat-note').textContent=repeatNote()}if(b.dataset.week){document.querySelectorAll('[data-week]').forEach(x=>x.classList.toggle('selected',x===b));const card=b.closest('.week-card');card.querySelector('.badge').textContent=b.dataset.week+'周';card.querySelector('.subtle').textContent='手动调整 · 下周为'+(b.dataset.week==='单休'?'双休':'单休')+'周';toast('本周安排已调整（预览）')}if(b.dataset.tip)toast(b.dataset.tip);if(b.dataset.duration){document.querySelector('#timer-value').textContent='00:'+b.dataset.duration.padStart(2,'0')+':00';document.querySelectorAll('[data-duration]').forEach(x=>x.classList.toggle('selected',x===b))}if(b.id==='logo'){taps=Math.min(7,taps+1);b.classList.remove('bump');void b.offsetWidth;b.classList.add('bump');document.querySelectorAll('.tap-progress i').forEach((x,i)=>x.classList.toggle('filled',i<taps));document.querySelector('.egg-hint').textContent=taps<7?`再点 ${7-taps} 次，唤醒战马`:'战马已醒，轻点可再见一面';if(taps===7){unlocked=true;hideToast();document.querySelector('#reward').showModal()}}if(b.id==='motion'){const off=document.body.classList.toggle('no-motion');b.textContent='动效：'+(off?'关闭':'开启');b.setAttribute('aria-pressed',String(!off))}if(b.id==='start-watch'){if(stopwatchStart){elapsed+=Date.now()-stopwatchStart;stopwatchStart=0;clearInterval(interval);b.innerHTML=icon('play')+'继续'}else{stopwatchStart=Date.now();interval=setInterval(updateWatch,35);b.innerHTML=icon('pause')+'暂停'}}if(b.id==='reset-watch'){clearInterval(interval);stopwatchStart=0;elapsed=0;updateWatch();document.querySelector('#start-watch').innerHTML=icon('play')+'开始'}});
function updateWatch(){const ms=elapsed+(stopwatchStart?Date.now()-stopwatchStart:0);document.querySelector('#stopwatch-value').textContent=String(Math.floor(ms/60000)).padStart(2,'0')+':'+String(Math.floor(ms/1000)%60).padStart(2,'0')+'.'+String(Math.floor(ms/10)%100).padStart(2,'0')}
document.addEventListener('submit',e=>{if(e.target.id!=='alarm-form')return;e.preventDefault();const f=new FormData(e.target);const a={time:String(f.get('hour')).padStart(2,'0')+':'+String(f.get('minute')).padStart(2,'0'),name:String(f.get('name')).trim()||'新的清晨',repeat,enabled:true};if(editingId===null)alarms.push(a);else alarms[editingId]=a;go('home');toast('已保存，新的清晨准备好了')});
document.querySelector('#reward').addEventListener('click',e=>{if(e.target===e.currentTarget)e.currentTarget.close()});
function positionReward(){const box=document.querySelector('.phone').getBoundingClientRect();const modal=document.querySelector('#reward');Object.assign(modal.style,{position:'fixed',inset:'auto',left:(box.left+box.width/2)+'px',top:(box.top+box.height/2)+'px',margin:'0',transform:'translate(-50%, -50%)',width:(box.width-44)+'px',maxHeight:(box.height-60)+'px',overflowY:'auto'});}
window.addEventListener('resize',positionReward);
positionReward();
render();
